// <auto-generated />
using System;
using Kiroku.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiroku.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312171452_RenameAnimeIdToUserMalId")]
    partial class RenameAnimeIdToUserMalId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiroku.Domain.Entities.Aired", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("From")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from");

                    b.Property<int?>("PropId")
                        .HasColumnType("integer")
                        .HasColumnName("propid");

                    b.Property<string>("String")
                        .HasColumnType("text")
                        .HasColumnName("string");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_aireds");

                    b.HasIndex("PropId")
                        .IsUnique()
                        .HasDatabaseName("ix_aireds_propid");

                    b.ToTable("aireds");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AiredProp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromId")
                        .HasColumnType("integer")
                        .HasColumnName("fromid");

                    b.Property<int?>("ToId")
                        .HasColumnType("integer")
                        .HasColumnName("toid");

                    b.HasKey("Id")
                        .HasName("pk_airedprops");

                    b.HasIndex("FromId")
                        .IsUnique()
                        .HasDatabaseName("ix_airedprops_fromid");

                    b.HasIndex("ToId")
                        .IsUnique()
                        .HasDatabaseName("ix_airedprops_toid");

                    b.ToTable("airedprops");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AiredPropDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_airedpropdates");

                    b.ToTable("airedpropdates");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiredId")
                        .HasColumnType("integer")
                        .HasColumnName("airedid");

                    b.Property<bool>("Airing")
                        .HasColumnType("boolean")
                        .HasColumnName("airing");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean")
                        .HasColumnName("approved");

                    b.Property<string>("Background")
                        .HasColumnType("text")
                        .HasColumnName("background");

                    b.Property<int?>("BroadcastId")
                        .HasColumnType("integer")
                        .HasColumnName("broadcastid");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<int?>("Episodes")
                        .HasColumnType("integer")
                        .HasColumnName("episodes");

                    b.Property<int?>("Favorites")
                        .HasColumnType("integer")
                        .HasColumnName("favorites");

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<int?>("Members")
                        .HasColumnType("integer")
                        .HasColumnName("members");

                    b.Property<int?>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Rating")
                        .HasColumnType("text")
                        .HasColumnName("rating");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int?>("ScoredBy")
                        .HasColumnType("integer")
                        .HasColumnName("scoredby");

                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("text")
                        .HasColumnName("titleenglish");

                    b.Property<string>("TitleJapanese")
                        .HasColumnType("text")
                        .HasColumnName("titlejapanese");

                    b.Property<int?>("TrailerId")
                        .HasColumnType("integer")
                        .HasColumnName("trailerid");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_animes");

                    b.HasIndex("AiredId")
                        .IsUnique()
                        .HasDatabaseName("ix_animes_airedid");

                    b.HasIndex("BroadcastId")
                        .IsUnique()
                        .HasDatabaseName("ix_animes_broadcastid");

                    b.HasIndex("TrailerId")
                        .IsUnique()
                        .HasDatabaseName("ix_animes_trailerid");

                    b.ToTable("animes");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    b.Property<int>("Favorites")
                        .HasColumnType("integer")
                        .HasColumnName("favorites");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_animecharacters");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_animecharacters_animeid");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_animecharacters_characterid");

                    b.ToTable("animecharacters");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genreid");

                    b.HasKey("AnimeId", "GenreId")
                        .HasName("pk_animegenres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_animegenres_genreid");

                    b.ToTable("animegenres");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Format")
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("LargeImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("largeimageurl");

                    b.Property<string>("SmallImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("smallimageurl");

                    b.HasKey("Id")
                        .HasName("pk_animeimages");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_animeimages_animeid");

                    b.ToTable("animeimages");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeLicensor", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("LicensorId")
                        .HasColumnType("integer")
                        .HasColumnName("licensorid");

                    b.HasKey("AnimeId", "LicensorId")
                        .HasName("pk_animelicensors");

                    b.HasIndex("LicensorId")
                        .HasDatabaseName("ix_animelicensors_licensorid");

                    b.ToTable("animelicensors");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeProducer", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer")
                        .HasColumnName("producerid");

                    b.HasKey("AnimeId", "ProducerId")
                        .HasName("pk_animeproducers");

                    b.HasIndex("ProducerId")
                        .HasDatabaseName("ix_animeproducers_producerid");

                    b.ToTable("animeproducers");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeStudio", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("StudioId")
                        .HasColumnType("integer")
                        .HasColumnName("studioid");

                    b.HasKey("AnimeId", "StudioId")
                        .HasName("pk_animestudios");

                    b.HasIndex("StudioId")
                        .HasDatabaseName("ix_animestudios_studioid");

                    b.ToTable("animestudios");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_animetitles");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_animetitles_animeid");

                    b.ToTable("animetitles");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeTitleSynonym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Synonym")
                        .HasColumnType("text")
                        .HasColumnName("synonym");

                    b.HasKey("Id")
                        .HasName("pk_animetitlesynonyms");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_animetitlesynonyms_animeid");

                    b.ToTable("animetitlesynonyms");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Broadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<string>("String")
                        .HasColumnType("text")
                        .HasColumnName("string");

                    b.Property<string>("Time")
                        .HasColumnType("text")
                        .HasColumnName("time");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("pk_broadcasts");

                    b.ToTable("broadcasts");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Favorites")
                        .HasColumnType("integer")
                        .HasColumnName("favorites");

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.CharacterImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.HasKey("Id")
                        .HasName("pk_characterimages");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_characterimages_characterid");

                    b.ToTable("characterimages");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.CharacterVoice", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("characterid");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("personid");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("CharacterId", "PersonId", "Language")
                        .HasName("pk_charactervoices");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_charactervoices_personid");

                    b.ToTable("charactervoices");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.ExternalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_externallinks");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_externallinks_animeid");

                    b.ToTable("externallinks");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Licensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_licensors");

                    b.ToTable("licensors");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "mal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Chapters")
                        .HasColumnType("integer")
                        .HasColumnName("chapters")
                        .HasAnnotation("Relational:JsonPropertyName", "chapters");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageurl")
                        .HasAnnotation("Relational:JsonPropertyName", "image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis")
                        .HasAnnotation("Relational:JsonPropertyName", "synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.Property<int?>("Volumes")
                        .HasColumnType("integer")
                        .HasColumnName("volumes")
                        .HasAnnotation("Relational:JsonPropertyName", "volumes");

                    b.HasKey("Id")
                        .HasName("pk_mangas");

                    b.ToTable("mangas");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<int?>("MangaId")
                        .HasColumnType("integer")
                        .HasColumnName("mangaid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("MangaId")
                        .HasDatabaseName("ix_people_mangaid");

                    b.ToTable("people");

                    b.HasAnnotation("Relational:JsonPropertyName", "authors");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.PersonImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("personid");

                    b.HasKey("Id")
                        .HasName("pk_personimages");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_personimages_personid");

                    b.ToTable("personimages");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_producers");

                    b.ToTable("producers");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("RelationType")
                        .HasColumnType("text")
                        .HasColumnName("relationtype");

                    b.HasKey("Id")
                        .HasName("pk_relations");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_relations_animeid");

                    b.ToTable("relations");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.RelationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntryType")
                        .HasColumnType("text")
                        .HasColumnName("entrytype");

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RelationId")
                        .HasColumnType("integer")
                        .HasColumnName("relationid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_relationentries");

                    b.HasIndex("RelationId")
                        .HasDatabaseName("ix_relationentries_relationid");

                    b.ToTable("relationentries");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.StreamingLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_streaminglinks");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_streaminglinks_animeid");

                    b.ToTable("streaminglinks");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MalId")
                        .HasColumnType("integer")
                        .HasColumnName("malid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_studios");

                    b.ToTable("studios");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.ThemeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("rawtext");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_themeentries");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_themeentries_animeid");

                    b.ToTable("themeentries");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmbedUrl")
                        .HasColumnType("text")
                        .HasColumnName("embedurl");

                    b.Property<int?>("TrailerImagesId")
                        .HasColumnType("integer")
                        .HasColumnName("trailerimagesid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("YoutubeId")
                        .HasColumnType("text")
                        .HasColumnName("youtubeid");

                    b.HasKey("Id")
                        .HasName("pk_trailers");

                    b.HasIndex("TrailerImagesId")
                        .IsUnique()
                        .HasDatabaseName("ix_trailers_trailerimagesid");

                    b.ToTable("trailers");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.TrailerImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<string>("LargeImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("largeimageurl");

                    b.Property<string>("MaximumImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("maximumimageurl");

                    b.Property<string>("MediumImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("mediumimageurl");

                    b.Property<string>("SmallImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("smallimageurl");

                    b.HasKey("Id")
                        .HasName("pk_trailerimages");

                    b.ToTable("trailerimages");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("MalUserId")
                        .HasColumnType("integer")
                        .HasColumnName("maluserid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text")
                        .HasColumnName("profilepicture");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.UserAnimeList", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer")
                        .HasColumnName("animeid");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId", "AnimeId")
                        .HasName("pk_useranimelists");

                    b.HasIndex("AnimeId")
                        .HasDatabaseName("ix_useranimelists_animeid");

                    b.ToTable("useranimelists");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Aired", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.AiredProp", "Prop")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.Aired", "PropId")
                        .HasConstraintName("fk_aireds_airedprops_propid");

                    b.Navigation("Prop");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AiredProp", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.AiredPropDate", "From")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.AiredProp", "FromId")
                        .HasConstraintName("fk_airedprops_airedpropdates_fromid");

                    b.HasOne("Kiroku.Domain.Entities.AiredPropDate", "To")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.AiredProp", "ToId")
                        .HasConstraintName("fk_airedprops_airedpropdates_toid");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Anime", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Aired", "Aired")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.Anime", "AiredId")
                        .HasConstraintName("fk_animes_aireds_airedid");

                    b.HasOne("Kiroku.Domain.Entities.Broadcast", "Broadcast")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.Anime", "BroadcastId")
                        .HasConstraintName("fk_animes_broadcasts_broadcastid");

                    b.HasOne("Kiroku.Domain.Entities.Trailer", "Trailer")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.Anime", "TrailerId")
                        .HasConstraintName("fk_animes_trailers_trailerid");

                    b.Navigation("Aired");

                    b.Navigation("Broadcast");

                    b.Navigation("Trailer");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeCharacter", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animecharacters_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.Character", "Character")
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animecharacters_characters_characterid");

                    b.Navigation("Anime");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeGenre", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animegenres_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animegenres_genres_genreid");

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeImage", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("Images")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animeimages_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeLicensor", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("AnimeLicensors")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animelicensors_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.Licensor", "Licensor")
                        .WithMany("AnimeLicensors")
                        .HasForeignKey("LicensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animelicensors_licensors_licensorid");

                    b.Navigation("Anime");

                    b.Navigation("Licensor");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeProducer", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("AnimeProducers")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animeproducers_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.Producer", "Producer")
                        .WithMany("AnimeProducers")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animeproducers_producers_producerid");

                    b.Navigation("Anime");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeStudio", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("AnimeStudios")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animestudios_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.Studio", "Studio")
                        .WithMany("AnimeStudios")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animestudios_studios_studioid");

                    b.Navigation("Anime");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeTitle", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("Titles")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animetitles_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.AnimeTitleSynonym", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("TitleSynonyms")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animetitlesynonyms_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.CharacterImage", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Character", "Character")
                        .WithMany("Images")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characterimages_characters_characterid");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.CharacterVoice", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Character", "Character")
                        .WithMany("CharacterVoices")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charactervoices_characters_characterid");

                    b.HasOne("Kiroku.Domain.Entities.Person", "Person")
                        .WithMany("CharacterVoices")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charactervoices_people_personid");

                    b.Navigation("Character");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.ExternalLink", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_externallinks_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Person", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Manga", null)
                        .WithMany("Authors")
                        .HasForeignKey("MangaId")
                        .HasConstraintName("fk_people_mangas_mangaid");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.PersonImage", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Person", "Person")
                        .WithMany("Images")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personimages_people_personid");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Relation", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("Relations")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relations_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.RelationEntry", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Relation", "Relation")
                        .WithMany("Entries")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationentries_relations_relationid");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.StreamingLink", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("StreamingLinks")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_streaminglinks_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.ThemeEntry", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany("ThemeEntries")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_themeentries_animes_animeid");

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Trailer", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.TrailerImages", "Images")
                        .WithOne()
                        .HasForeignKey("Kiroku.Domain.Entities.Trailer", "TrailerImagesId")
                        .HasConstraintName("fk_trailers_trailerimages_trailerimagesid");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.UserAnimeList", b =>
                {
                    b.HasOne("Kiroku.Domain.Entities.Anime", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_useranimelists_animes_animeid");

                    b.HasOne("Kiroku.Domain.Entities.User", "User")
                        .WithMany("AnimeList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_useranimelists_users_userid");

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Anime", b =>
                {
                    b.Navigation("AnimeGenres");

                    b.Navigation("AnimeLicensors");

                    b.Navigation("AnimeProducers");

                    b.Navigation("AnimeStudios");

                    b.Navigation("ExternalLinks");

                    b.Navigation("Images");

                    b.Navigation("Relations");

                    b.Navigation("StreamingLinks");

                    b.Navigation("ThemeEntries");

                    b.Navigation("TitleSynonyms");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Character", b =>
                {
                    b.Navigation("AnimeCharacters");

                    b.Navigation("CharacterVoices");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Licensor", b =>
                {
                    b.Navigation("AnimeLicensors");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Manga", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Person", b =>
                {
                    b.Navigation("CharacterVoices");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Producer", b =>
                {
                    b.Navigation("AnimeProducers");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Relation", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.Studio", b =>
                {
                    b.Navigation("AnimeStudios");
                });

            modelBuilder.Entity("Kiroku.Domain.Entities.User", b =>
                {
                    b.Navigation("AnimeList");
                });
#pragma warning restore 612, 618
        }
    }
}
